using System.Linq;
using UnityEngine;

public class CollisionTriggeredTeleport : MonoBehaviour
{
    // Inspector Editor is generated by Assets/Editor/CollisionTriggeredTeleportEditor

    public enum DetectUsing
    {
        Tag, Layer
    }

    public enum TeleportMode
    {
        Relative, Absolute
    }

    private static string defaultTagName = "Untagged";
    private static string defaultLayerName = "Default";

    [Tooltip("Determine if the colliding Object or its parent should be transformed")]
    [SerializeField] private bool _transformParent = false;

    [Tooltip("Whether the Teleportation should be relative to the objects current position or absolute")]
    [SerializeField] private TeleportMode _vectorType = TeleportMode.Relative;

    [Tooltip("The Vector to be applied to the specified GameObject")]
    [SerializeField] private Vector3 _teleportVector = Vector3.zero;

    // Variable used in Assets/Editor/CollisionTriggeredTeleportEditor
    [Tooltip("How to detect the colliding Object")]
    public DetectUsing detectUsing = DetectUsing.Tag;

    [Tooltip("The tag collision has to be detected for")]
    [SerializeField] private string _collidingTag = defaultTagName;

    [Tooltip("The layer collision has to be detected for")]
    [SerializeField] private string _collidingLayer = defaultLayerName;

    // Layer comparison is done in int, calculation result of the layer conversion to int is saved
    private int _collidingLayerInt = -1;


    // Start is called before the first frame update
    void Start()
    {
        // Check with the appropriate detection type if the tag or layer exists
        if (detectUsing == DetectUsing.Tag)
        {
            // Does the Unity Editor have a tag with that name registered?
            if (!UnityEditorInternal.InternalEditorUtility.tags.Contains<string>(_collidingTag))
            {
                throw new System.Exception("Unregistered Tag used in Trigger Area GameObject");
            }
        } else
        {
            _collidingLayerInt = LayerMask.NameToLayer(_collidingLayer);
            // Does a layer with that name exist (-1 means an non-existant layer)
            if (_collidingLayerInt == -1)
            {
                throw new System.Exception("Unregistered Layer used in Trigger Area GameObject");
            }
        }
    }

    // OnTriggerEnter is called every time this GameObject's collider detects a collision with another GameObject
    private void OnTriggerEnter(Collider other)
    {
        // Detect if the other GameObject has the correct Tag or Layer (depending on the choosen detection type)
        if (detectUsing == DetectUsing.Tag)
        {
            if (!other.gameObject.CompareTag(_collidingTag)) return;
        } else
        {
            if (other.gameObject.layer != _collidingLayerInt) return;
        }

        // Get the Transform component of the actual GameObject to teleport
        Transform _gameObjectToTeleport;
        
        if(_transformParent)
        {
            _gameObjectToTeleport = other.gameObject.GetComponentInParent<Transform>();
        } else
        {
            _gameObjectToTeleport = other.gameObject.GetComponent<Transform>();
        }
        
        // Teleport relative to the current position of the GameObject or the absolute position in the World
        if(_vectorType == TeleportMode.Relative)
        {
            _gameObjectToTeleport.Translate(_teleportVector);
        } else
        {
            _gameObjectToTeleport.position = _teleportVector;
        }
    }
}
